-- InfoMapper · initial schema (data model v2, docs/data-model-v2.md)
-- Portable core (AD-18): no enum types, no triggers, no stored functions, no arrays.
-- Ids are UUID v7 generated by the application (AD-11). Writes go through the application server (AD-23).
-- Row Level Security is enabled in the next migration (20261002000100_enable_rls.sql).

-- ============================================================
-- Tenancy and access
-- ============================================================

create table app_user (
  id            uuid primary key,
  email         text not null,
  display_name  text not null,
  created_at    timestamptz not null,
  last_seen_at  timestamptz,
  constraint app_user_email_lower check (email = lower(email))
);
create unique index app_user_email_uq on app_user (email);

create table organization (
  id          uuid primary key,
  name        text not null,
  version     integer not null default 1,
  created_at  timestamptz not null,
  created_by  uuid not null references app_user (id),
  updated_at  timestamptz not null,
  updated_by  uuid not null references app_user (id),
  deleted_at  timestamptz
);

create table organization_member (
  organization_id  uuid not null references organization (id),
  user_id          uuid not null references app_user (id),
  role             text not null,
  created_at       timestamptz not null,
  primary key (organization_id, user_id),
  constraint organization_member_role_ck check (role in ('owner', 'admin', 'member'))
);
create index organization_member_user_ix on organization_member (user_id);

create table workspace (
  id                    uuid primary key,
  organization_id       uuid not null references organization (id),
  name                  text not null,
  client_name           text,
  description           text,
  doc_language          text not null default 'en',
  dv2_mode              boolean not null default false,
  four_eyes             boolean not null default false,
  archived_at           timestamptz,
  archived_by           uuid references app_user (id),
  requirement_key_next  integer not null default 101,
  version               integer not null default 1,
  created_at            timestamptz not null,
  created_by            uuid not null references app_user (id),
  updated_at            timestamptz not null,
  updated_by            uuid not null references app_user (id),
  deleted_at            timestamptz,
  constraint workspace_doc_language_ck check (doc_language in ('en', 'pl', 'de'))
);
create index workspace_organization_ix on workspace (organization_id);

create table workspace_member (
  workspace_id  uuid not null references workspace (id),
  user_id       uuid not null references app_user (id),
  role          text not null,
  added_by      uuid references app_user (id),
  created_at    timestamptz not null,
  primary key (workspace_id, user_id),
  constraint workspace_member_role_ck check (role in ('owner', 'admin', 'modeler', 'reviewer', 'reader'))
);
create index workspace_member_user_ix on workspace_member (user_id);

create table invitation (
  id            uuid primary key,
  workspace_id  uuid not null references workspace (id),
  email         text not null,
  role          text not null,
  token_hash    text not null,
  invited_by    uuid not null references app_user (id),
  created_at    timestamptz not null,
  expires_at    timestamptz not null,
  accepted_at   timestamptz,
  revoked_at    timestamptz,
  constraint invitation_email_lower check (email = lower(email)),
  constraint invitation_role_ck check (role in ('admin', 'modeler', 'reviewer', 'reader'))
);
create unique index invitation_token_uq on invitation (token_hash);
create index invitation_workspace_ix on invitation (workspace_id);

-- ============================================================
-- Model
-- Standard columns on every model and work table:
--   id, workspace_id, version, created_at/by, updated_at/by, deleted_at   (AD-12)
-- ============================================================

create table concept (
  id                uuid primary key,
  workspace_id      uuid not null references workspace (id),
  name              text not null,
  description_html  text,
  description_text  text,
  color             text not null,
  sort_order        integer not null default 0,
  version           integer not null default 1,
  created_at        timestamptz not null,
  created_by        uuid not null references app_user (id),
  updated_at        timestamptz not null,
  updated_by        uuid not null references app_user (id),
  deleted_at        timestamptz,
  constraint concept_color_ck check (color like '#______')   -- shape only; hex digits are checked in the domain (portable, AD-18)
);
create index concept_workspace_ix on concept (workspace_id);

create table entity (
  id               uuid primary key,
  workspace_id     uuid not null references workspace (id),
  concept_id       uuid not null references concept (id),
  name             text not null,
  stereotype       text not null default 'object',
  definition_html  text,
  definition_text  text,
  version          integer not null default 1,
  created_at       timestamptz not null,
  created_by       uuid not null references app_user (id),
  updated_at       timestamptz not null,
  updated_by       uuid not null references app_user (id),
  deleted_at       timestamptz,
  constraint entity_stereotype_ck check (stereotype in ('object', 'link', 'dictionary', 'context', 'informative'))
);
create index entity_workspace_ix on entity (workspace_id);
create index entity_concept_ix on entity (concept_id);

create table attribute (
  id               uuid primary key,
  workspace_id     uuid not null references workspace (id),
  entity_id        uuid not null references entity (id),
  name             text not null,
  sort_order       integer not null,
  data_type        text not null default 'string',
  custom_type      text,
  type_length      integer,
  type_precision   integer,
  type_scale       integer,
  is_primary_key   boolean not null default false,
  is_foreign_key   boolean not null default false,
  is_business_key  boolean not null default false,
  is_pii           boolean not null default false,
  is_nullable      boolean not null default true,
  definition_html  text,
  definition_text  text,
  version          integer not null default 1,
  created_at       timestamptz not null,
  created_by       uuid not null references app_user (id),
  updated_at       timestamptz not null,
  updated_by       uuid not null references app_user (id),
  deleted_at       timestamptz,
  constraint attribute_data_type_ck check (data_type in ('string', 'integer', 'decimal', 'boolean', 'date', 'datetime', 'json', 'custom')),
  constraint attribute_custom_type_ck check ((data_type = 'custom') = (custom_type is not null)),
  constraint attribute_type_params_ck check (
    (type_length is null or type_length > 0) and
    (type_precision is null or type_precision > 0) and
    (type_scale is null or (type_scale >= 0 and type_precision is not null and type_scale <= type_precision)))
);
create index attribute_workspace_ix on attribute (workspace_id);
create index attribute_entity_ix on attribute (entity_id, sort_order);

create table relationship (
  id              uuid primary key,
  workspace_id    uuid not null references workspace (id),
  from_entity_id  uuid not null references entity (id),
  to_entity_id    uuid not null references entity (id),
  label           text,
  from_min        smallint not null default 1,
  from_max        text not null default '1',
  to_min          smallint not null default 0,
  to_max          text not null default 'n',
  description     text,
  version         integer not null default 1,
  created_at      timestamptz not null,
  created_by      uuid not null references app_user (id),
  updated_at      timestamptz not null,
  updated_by      uuid not null references app_user (id),
  deleted_at      timestamptz,
  constraint relationship_min_ck check (from_min in (0, 1) and to_min in (0, 1)),
  constraint relationship_max_ck check (from_max in ('1', 'n') and to_max in ('1', 'n'))
);
create index relationship_workspace_ix on relationship (workspace_id);
create index relationship_from_ix on relationship (from_entity_id);
create index relationship_to_ix on relationship (to_entity_id);

-- ============================================================
-- Sources
-- ============================================================

create table source_system (
  id            uuid primary key,
  workspace_id  uuid not null references workspace (id),
  name          text not null,
  description   text,
  version       integer not null default 1,
  created_at    timestamptz not null,
  created_by    uuid not null references app_user (id),
  updated_at    timestamptz not null,
  updated_by    uuid not null references app_user (id),
  deleted_at    timestamptz
);
create unique index source_system_name_uq on source_system (workspace_id, name) where deleted_at is null;

create table source_table (
  id                uuid primary key,
  workspace_id      uuid not null references workspace (id),
  source_system_id  uuid not null references source_system (id),
  database_name     text not null,
  schema_name       text not null,
  name              text not null,
  object_type       text not null default 'table',
  row_count         bigint,
  comment           text,
  version           integer not null default 1,
  created_at        timestamptz not null,
  created_by        uuid not null references app_user (id),
  updated_at        timestamptz not null,
  updated_by        uuid not null references app_user (id),
  deleted_at        timestamptz,
  constraint source_table_object_type_ck check (object_type in ('table', 'view'))
);
create index source_table_workspace_ix on source_table (workspace_id);
create unique index source_table_name_uq on source_table (source_system_id, database_name, schema_name, name) where deleted_at is null;

create table source_column (
  id               uuid primary key,
  workspace_id     uuid not null references workspace (id),
  source_table_id  uuid not null references source_table (id),
  name             text not null,
  ordinal          integer not null,
  data_type        text not null,
  type_length      integer,
  type_precision   integer,
  type_scale       integer,
  is_nullable      boolean not null default true,
  is_primary_key   boolean not null default false,
  is_foreign_key   boolean not null default false,
  is_business_key  boolean not null default false,
  is_pii           boolean not null default false,
  default_value    text,
  comment          text,
  version          integer not null default 1,
  created_at       timestamptz not null,
  created_by       uuid not null references app_user (id),
  updated_at       timestamptz not null,
  updated_by       uuid not null references app_user (id),
  deleted_at       timestamptz
);
create index source_column_workspace_ix on source_column (workspace_id);
create index source_column_table_ix on source_column (source_table_id, ordinal);
create unique index source_column_name_uq on source_column (source_table_id, name) where deleted_at is null;

-- ============================================================
-- Mappings (AD-26: one mapping reads one or more columns)
-- ============================================================

create table mapping (
  id               uuid primary key,
  workspace_id     uuid not null references workspace (id),
  attribute_id     uuid not null references attribute (id),
  kind             text not null default 'direct',
  rule_expression  text,
  status           text not null default 'draft',
  note_html        text,
  note_text        text,
  approved_by      uuid references app_user (id),
  approved_at      timestamptz,
  version          integer not null default 1,
  created_at       timestamptz not null,
  created_by       uuid not null references app_user (id),
  updated_at       timestamptz not null,
  updated_by       uuid not null references app_user (id),
  deleted_at       timestamptz,
  constraint mapping_kind_ck check (kind in ('direct', 'transform')),
  constraint mapping_status_ck check (status in ('draft', 'review', 'approved')),
  constraint mapping_rule_ck check (kind = 'direct' or rule_expression is not null),
  constraint mapping_approval_ck check ((status = 'approved') = (approved_at is not null))
);
create index mapping_workspace_ix on mapping (workspace_id);
create index mapping_attribute_ix on mapping (attribute_id);

create table mapping_input (
  id                uuid primary key,
  workspace_id      uuid not null references workspace (id),
  mapping_id        uuid not null references mapping (id),
  source_column_id  uuid not null references source_column (id),
  sort_order        integer not null default 0,
  version           integer not null default 1,
  created_at        timestamptz not null,
  created_by        uuid not null references app_user (id),
  updated_at        timestamptz not null,
  updated_by        uuid not null references app_user (id),
  deleted_at        timestamptz
);
create index mapping_input_workspace_ix on mapping_input (workspace_id);
create index mapping_input_column_ix on mapping_input (source_column_id);
create unique index mapping_input_uq on mapping_input (mapping_id, source_column_id) where deleted_at is null;

-- ============================================================
-- Requirements
-- ============================================================

create table requirement (
  id                uuid primary key,
  workspace_id      uuid not null references workspace (id),
  key               text not null,
  kind              text not null,
  name              text not null,
  description_html  text,
  description_text  text,
  expression        text,
  severity          text,
  status            text not null default 'draft',
  priority          text not null default 'should',
  owner_name        text,
  external_ref      text,
  parent_id         uuid references requirement (id),
  version           integer not null default 1,
  created_at        timestamptz not null,
  created_by        uuid not null references app_user (id),
  updated_at        timestamptz not null,
  updated_by        uuid not null references app_user (id),
  deleted_at        timestamptz,
  constraint requirement_kind_ck check (kind in ('need', 'data', 'business_rule', 'dq_rule', 'non_functional')),
  constraint requirement_status_ck check (status in ('draft', 'agreed', 'implemented', 'verified')),
  constraint requirement_priority_ck check (priority in ('must', 'should', 'could', 'wont')),
  constraint requirement_severity_ck check (severity is null or (kind = 'dq_rule' and severity in ('warn', 'block'))),
  constraint requirement_not_own_parent_ck check (parent_id is null or parent_id <> id)
);
create unique index requirement_key_uq on requirement (workspace_id, key);
create index requirement_parent_ix on requirement (parent_id);

create table requirement_link (
  id                uuid primary key,
  workspace_id      uuid not null references workspace (id),
  requirement_id    uuid not null references requirement (id),
  entity_id         uuid references entity (id),
  attribute_id      uuid references attribute (id),
  mapping_id        uuid references mapping (id),
  source_table_id   uuid references source_table (id),
  source_column_id  uuid references source_column (id),
  version           integer not null default 1,
  created_at        timestamptz not null,
  created_by        uuid not null references app_user (id),
  updated_at        timestamptz not null,
  updated_by        uuid not null references app_user (id),
  deleted_at        timestamptz,
  constraint requirement_link_one_target_ck check (
    (case when entity_id is null then 0 else 1 end) + (case when attribute_id is null then 0 else 1 end) +
    (case when mapping_id is null then 0 else 1 end) + (case when source_table_id is null then 0 else 1 end) +
    (case when source_column_id is null then 0 else 1 end) = 1)
);
create index requirement_link_workspace_ix on requirement_link (workspace_id);
create index requirement_link_requirement_ix on requirement_link (requirement_id);
create index requirement_link_entity_ix on requirement_link (entity_id);
create index requirement_link_attribute_ix on requirement_link (attribute_id);
create index requirement_link_mapping_ix on requirement_link (mapping_id);
create index requirement_link_table_ix on requirement_link (source_table_id);
create index requirement_link_column_ix on requirement_link (source_column_id);

-- ============================================================
-- Working layer
-- ============================================================

create table label (
  id            uuid primary key,
  workspace_id  uuid not null references workspace (id),
  name          text not null,
  name_key      text not null,
  version       integer not null default 1,
  created_at    timestamptz not null,
  created_by    uuid not null references app_user (id),
  updated_at    timestamptz not null,
  updated_by    uuid not null references app_user (id),
  deleted_at    timestamptz,
  constraint label_name_key_ck check (name_key = lower(name))
);
create unique index label_name_uq on label (workspace_id, name_key) where deleted_at is null;

create table label_link (
  id                uuid primary key,
  workspace_id      uuid not null references workspace (id),
  label_id          uuid not null references label (id),
  entity_id         uuid references entity (id),
  attribute_id      uuid references attribute (id),
  mapping_id        uuid references mapping (id),
  source_table_id   uuid references source_table (id),
  source_column_id  uuid references source_column (id),
  version           integer not null default 1,
  created_at        timestamptz not null,
  created_by        uuid not null references app_user (id),
  updated_at        timestamptz not null,
  updated_by        uuid not null references app_user (id),
  deleted_at        timestamptz,
  constraint label_link_one_target_ck check (
    (case when entity_id is null then 0 else 1 end) + (case when attribute_id is null then 0 else 1 end) +
    (case when mapping_id is null then 0 else 1 end) + (case when source_table_id is null then 0 else 1 end) +
    (case when source_column_id is null then 0 else 1 end) = 1)
);
create index label_link_workspace_ix on label_link (workspace_id);
create index label_link_label_ix on label_link (label_id);
create index label_link_entity_ix on label_link (entity_id);
create index label_link_attribute_ix on label_link (attribute_id);
create index label_link_mapping_ix on label_link (mapping_id);
create index label_link_table_ix on label_link (source_table_id);
create index label_link_column_ix on label_link (source_column_id);

-- ============================================================
-- Organisation of work
-- ============================================================

create table project (
  id            uuid primary key,
  workspace_id  uuid not null references workspace (id),
  name          text not null,
  description   text,
  version       integer not null default 1,
  created_at    timestamptz not null,
  created_by    uuid not null references app_user (id),
  updated_at    timestamptz not null,
  updated_by    uuid not null references app_user (id),
  deleted_at    timestamptz
);
create index project_workspace_ix on project (workspace_id);

create table canvas (
  id             uuid primary key,
  workspace_id   uuid not null references workspace (id),
  name           text not null,
  live_label_id  uuid references label (id),
  look           jsonb not null default '{"background":"grey","grid":"dots","layer":"all"}',
  version        integer not null default 1,
  created_at     timestamptz not null,
  created_by     uuid not null references app_user (id),
  updated_at     timestamptz not null,
  updated_by     uuid not null references app_user (id),
  deleted_at     timestamptz
);
create index canvas_workspace_ix on canvas (workspace_id);
create unique index canvas_live_label_uq on canvas (live_label_id) where live_label_id is not null and deleted_at is null;

create table project_canvas (
  project_id    uuid not null references project (id),
  canvas_id     uuid not null references canvas (id),
  workspace_id  uuid not null references workspace (id),
  sort_order    integer not null default 0,
  added_at      timestamptz not null,
  added_by      uuid not null references app_user (id),
  primary key (project_id, canvas_id)
);
create index project_canvas_canvas_ix on project_canvas (canvas_id);

create table project_pinned_label (
  project_id    uuid not null references project (id),
  label_id      uuid not null references label (id),
  workspace_id  uuid not null references workspace (id),
  primary key (project_id, label_id)
);

create table frame (
  id                uuid primary key,
  workspace_id      uuid not null references workspace (id),
  canvas_id         uuid not null references canvas (id),
  name              text not null,
  kind              text not null default 'free',
  concept_id        uuid references concept (id),
  source_system_id  uuid references source_system (id),
  color             text,
  x                 numeric not null,
  y                 numeric not null,
  width             numeric not null,
  height            numeric not null,
  collapsed         boolean not null default false,
  version           integer not null default 1,
  created_at        timestamptz not null,
  created_by        uuid not null references app_user (id),
  updated_at        timestamptz not null,
  updated_by        uuid not null references app_user (id),
  deleted_at        timestamptz,
  constraint frame_kind_ck check (kind in ('concept', 'source_system', 'free')),
  constraint frame_ref_ck check (
    (kind = 'concept' and concept_id is not null and source_system_id is null) or
    (kind = 'source_system' and source_system_id is not null and concept_id is null) or
    (kind = 'free' and concept_id is null and source_system_id is null)),
  constraint frame_size_ck check (width > 0 and height > 0)
);
create index frame_canvas_ix on frame (canvas_id);

create table canvas_item (
  id               uuid primary key,
  workspace_id     uuid not null references workspace (id),
  canvas_id        uuid not null references canvas (id),
  entity_id        uuid references entity (id),
  source_table_id  uuid references source_table (id),
  requirement_id   uuid references requirement (id),
  x                numeric not null,
  y                numeric not null,
  width            integer,
  collapsed        boolean not null default false,
  row_filter       text not null default 'all',
  frame_id         uuid references frame (id),
  live_level       text,
  version          integer not null default 1,
  created_at       timestamptz not null,
  created_by       uuid not null references app_user (id),
  updated_at       timestamptz not null,
  updated_by       uuid not null references app_user (id),
  deleted_at       timestamptz,
  constraint canvas_item_one_target_ck check (
    (case when entity_id is null then 0 else 1 end) + (case when source_table_id is null then 0 else 1 end) +
    (case when requirement_id is null then 0 else 1 end) = 1),
  constraint canvas_item_width_ck check (width is null or width between 200 and 600),
  constraint canvas_item_row_filter_ck check (row_filter in ('all', 'mapped', 'unmapped', 'keys', 'labeled')),
  constraint canvas_item_live_level_ck check (live_level is null or live_level in ('full', 'context'))
);
create index canvas_item_canvas_ix on canvas_item (canvas_id);
create index canvas_item_frame_ix on canvas_item (frame_id);
create unique index canvas_item_entity_uq on canvas_item (canvas_id, entity_id) where entity_id is not null and deleted_at is null;
create unique index canvas_item_table_uq on canvas_item (canvas_id, source_table_id) where source_table_id is not null and deleted_at is null;
create unique index canvas_item_requirement_uq on canvas_item (canvas_id, requirement_id) where requirement_id is not null and deleted_at is null;

create table note (
  id                  uuid primary key,
  workspace_id        uuid not null references workspace (id),
  canvas_id           uuid not null references canvas (id),
  body_html           text,
  body_text           text,
  color               text not null default 'yellow',
  status              text not null default 'open',
  resolved_at         timestamptz,
  resolved_by         uuid references app_user (id),
  width               integer not null default 220,
  pin_canvas_item_id  uuid references canvas_item (id),
  pin_frame_id        uuid references frame (id),
  x                   numeric not null,
  y                   numeric not null,
  frame_id            uuid references frame (id),
  version             integer not null default 1,
  created_at          timestamptz not null,
  created_by          uuid not null references app_user (id),
  updated_at          timestamptz not null,
  updated_by          uuid not null references app_user (id),
  deleted_at          timestamptz,
  constraint note_color_ck check (color in ('yellow', 'blue', 'green', 'pink', 'grey')),
  constraint note_status_ck check (status in ('open', 'resolved')),
  constraint note_one_pin_ck check (pin_canvas_item_id is null or pin_frame_id is null),
  constraint note_pinned_not_in_frame_ck check ((pin_canvas_item_id is null and pin_frame_id is null) or frame_id is null),
  constraint note_width_ck check (width between 160 and 520)
);
create index note_canvas_ix on note (canvas_id);
create index note_open_ix on note (workspace_id, status);

-- ============================================================
-- History
-- ============================================================

create table change_event (
  id                uuid primary key,
  workspace_id      uuid not null references workspace (id),
  change_group_id   uuid not null,
  occurred_at       timestamptz not null,
  user_id           uuid not null references app_user (id),
  object_type       text not null,
  object_id         uuid not null,
  operation         text not null,
  before_image      jsonb,
  after_image       jsonb,
  context_label_id  uuid references label (id),
  constraint change_event_operation_ck check (operation in ('create', 'update', 'delete', 'restore')),
  constraint change_event_images_ck check (
    (operation = 'create' and before_image is null and after_image is not null) or
    (operation in ('update', 'restore') and before_image is not null and after_image is not null) or
    -- a removed link row (e.g. project_canvas) has no after state
    (operation = 'delete' and before_image is not null))
);
create index change_event_object_ix on change_event (object_id, occurred_at);
create index change_event_group_ix on change_event (change_group_id);
create index change_event_workspace_time_ix on change_event (workspace_id, occurred_at);

create table baseline (
  id               uuid primary key,
  workspace_id     uuid not null references workspace (id),
  name             text not null,
  note             text,
  created_at       timestamptz not null,
  created_by       uuid not null references app_user (id),
  snapshot         jsonb not null,
  snapshot_schema  integer not null default 1
);
create index baseline_workspace_ix on baseline (workspace_id, created_at);
